schema:
  name: CommonSchema
  version: 1.0.9
metadata:
  name: mnath-app2
  version: 1.0.9
configs:
  AppName: PriceDetector
  pressureRangeMax: ${{$val(PressureRangeMax)}}
  lengthRangeMax: ${{$val(LengthRangeMax)}}
  errorThreshold: ${{$val(ErrorThreshold)}}
  healthCheckEndpoint: ${{$val(HealthCheckEndpoint)}}
  enableLocalLog: ${{$val(EnableLocalLog)}}
  healthCheckEnabled: ${{$val(HealthCheckEnabled)}}
  applicationEndpoint: ${{$val(ApplicationEndpoint)}}
  SqlServerEndpoint: ${{$config(CommonConfig/1.0.9,SqlServerEndpoint)}}
  LineHealthEndpoint: ${{$config(CommonConfig/1.0.9,LineHealthEndpoint)}}
