schema:
  name: CommonSchema
  version: 1.0.9
metadata:
  name: CommonConfig
  version: 1.0.9
configs:
  SqlServerEndpoint: http://localhost/SqlServerEndpoint
  LineHealthEndpoint: http://localhost/LineHealthEndpoint
