schema:
  name: HotmeltSchema3
  version: 1.0.2
metadata:
  name: mnath-hotmelt4
  version: 1.0.2
configs:
  ErrorThreshold: ${{$val(ErrorThreshold)}}
  ${{$include(LogsettingsConfig/1.0.1)}}:
  ${{$include(ProtocolConfig/1.0.1, TCP)}}:
  TargetName: ${{$target(name)}}
