schema:
  name: LogsettingsSchema
  version: 1.0.1
metadata:
  name: LogsettingsConfig
  version: 1.0.1
configs:
  LogSettings:
    LogOutput:
      # EnableConsole: true
      EnableConsole: ${{$val(LogSettings.LogOutput.EnableConsole)}}
