schema:
  name: ProtocolSchema
  version: 1.0.1
metadata:
  name: ProtocolConfig
  version: 1.0.1
configs:
  SupportedHttpMethods: ${{$val(SupportedHttpMethods)}}
  TCP:
    EnableSSL: ${{$val(TCP.EnableSSL)}}
    